In [1]:
import numpy as np
import pandas as pd
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname,filename))

In [4]:
ds = pd.read_csv('train.csv')

In [5]:
ds.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4       0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel780  pixel781  pixel782  pixel783  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 785 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(ds.iloc[:,1:],ds.iloc[:,0],test_size=0.2,random_state=2)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [16]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [17]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [18]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [19]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression:",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Tree:",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression: 0.8605230386052304
Accuracy of Decision Tree: 0.7297633872976339


In [23]:
print("Confusion matrix of Logistic Regression\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Confusion matrix of Logistic Regression



0   1   2   3   4   5   6   7   8   9
0  77   0   0   0   0   1   1   0   0   0
1   0  96   1   1   0   1   0   1   3   0
2   2   0  77   5   0   1   2   2   2   0
3   0   0   1  59   0   5   1   2   1   0
4   0   1   0   0  67   0   2   0   1   2
5   2   3   1   2   1  50   3   0   4   1
6   1   0   1   0   0   3  70   0   0   0
7   1   1   1   0   0   0   0  75   0   4
8   0   2   3   7   0   5   1   1  59   2
9   1   1   0   4   4   4   0   8   1  61

In [24]:
print("Confusion matrix of Decision Tree\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Confusion matrix of Decision Tree



0   1   2   3   4   5   6   7   8   9
0  72   0   2   0   0   2   1   0   1   1
1   0  95   2   2   1   0   1   1   0   1
2   2   4  53   3   8   2   6   5   6   2
3   0   0   1  48   2   7   1   2   2   6
4   0   0   2   0  52   2   2   8   1   6
5   0   2   1   6   3  42   4   2   2   5
6   3   0   3   2   0   6  59   0   1   1
7   3   0   5   0   2   0   0  63   2   7
8   3   2   3   8   5   8   1   3  46   1
9   0   0   2   6   9   3   1   3   4  56

In [25]:
from sklearn.metrics import precision_score,recall_score,f1_score

**Logistic Regression score**

In [29]:
print("Macro precision:", precision_score(y_test,y_pred1,average='macro'))
print("Weighted precision:", precision_score(y_test,y_pred1,average='weighted'))
precision_score(y_test,y_pred1,average=None)

Macro precision: 0.8566988585071306
Weighted precision: 0.8621592612717127


array([0.91666667, 0.92307692, 0.90588235, 0.75641026, 0.93055556,
       0.71428571, 0.875     , 0.84269663, 0.83098592, 0.87142857])

In [30]:
print("Macro recall:", recall_score(y_test,y_pred1,average='macro'))
print("Weighted recall:", recall_score(y_test,y_pred1,average='weighted'))
recall_score(y_test,y_pred1,average=None)

Macro recall: 0.8583683520936989
Weighted recall: 0.8605230386052304


array([0.97468354, 0.93203883, 0.84615385, 0.85507246, 0.91780822,
       0.74626866, 0.93333333, 0.91463415, 0.7375    , 0.72619048])

In [31]:
print("Macro f1 score:", f1_score(y_test,y_pred1,average='macro'))
print("Weighted f1 score:", f1_score(y_test,y_pred1,average='weighted'))
f1_score(y_test,y_pred1,average=None)

Macro f1 score: 0.8558191069484735
Weighted f1 score: 0.8596363301775874


array([0.94478528, 0.92753623, 0.875     , 0.80272109, 0.92413793,
       0.72992701, 0.90322581, 0.87719298, 0.78145695, 0.79220779])

**Decision Tree score**

In [32]:
print("Macro precision:", precision_score(y_test,y_pred2,average='macro'))
print("Weighted precision:", precision_score(y_test,y_pred2,average='weighted'))
precision_score(y_test,y_pred2,average=None)

Macro precision: 0.7222804686516564
Weighted precision: 0.7312053125866864


array([0.86746988, 0.9223301 , 0.71621622, 0.64      , 0.63414634,
       0.58333333, 0.77631579, 0.72413793, 0.70769231, 0.65116279])

In [33]:
print("Macro recall:", recall_score(y_test,y_pred2,average='macro'))
print("Weighted recall:", recall_score(y_test,y_pred2,average='weighted'))
recall_score(y_test,y_pred2,average=None)

Macro recall: 0.7247612713506537
Weighted recall: 0.7297633872976339


array([0.91139241, 0.9223301 , 0.58241758, 0.69565217, 0.71232877,
       0.62686567, 0.78666667, 0.76829268, 0.575     , 0.66666667])

In [34]:
print("Macro f1 score:", f1_score(y_test,y_pred2,average='macro'))
print("Weighted f1 score:", f1_score(y_test,y_pred2,average='weighted'))
f1_score(y_test,y_pred2,average=None)

Macro f1 score: 0.7215919555617605
Weighted f1 score: 0.7285153741409597


array([0.88888889, 0.9223301 , 0.64242424, 0.66666667, 0.67096774,
       0.60431655, 0.78145695, 0.74556213, 0.63448276, 0.65882353])

In [39]:
#use classification_report for simplicity and less number of lines.
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94        79
           1       0.92      0.93      0.93       103
           2       0.91      0.85      0.88        91
           3       0.76      0.86      0.80        69
           4       0.93      0.92      0.92        73
           5       0.71      0.75      0.73        67
           6       0.88      0.93      0.90        75
           7       0.84      0.91      0.88        82
           8       0.83      0.74      0.78        80
           9       0.87      0.73      0.79        84

    accuracy                           0.86       803
   macro avg       0.86      0.86      0.86       803
weighted avg       0.86      0.86      0.86       803



In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.87      0.91      0.89        79
           1       0.92      0.92      0.92       103
           2       0.72      0.58      0.64        91
           3       0.64      0.70      0.67        69
           4       0.63      0.71      0.67        73
           5       0.58      0.63      0.60        67
           6       0.78      0.79      0.78        75
           7       0.72      0.77      0.75        82
           8       0.71      0.57      0.63        80
           9       0.65      0.67      0.66        84

    accuracy                           0.73       803
   macro avg       0.72      0.72      0.72       803
weighted avg       0.73      0.73      0.73       803

